services:
  frontend:
    image: maeddes/hse25frontend:flask
    container_name: frontend
    ports:
      - "5000:5000"
    environment:
      API_SERVER_URL: "http://api:3000"
    networks:
      - shoppingnet

  api:
    # Use when building from local Dockerfile
    #build:
    #  context: .
    #  dockerfile: Dockerfile

    # Use when pulling from GitHub Container Registry
    image: ghcr.io/hightier2244/distributed_systems:latest
    
    container_name: shopping_api
    ports:
      - "3000:3000"
    volumes:
      - sqlite_data:/app/db
    # Uncomment the following lines to connect to a PostgreSQL database
    # depends_on:
    #    - db
    # environment:
    #   POSTGRES_CONNECTION: "Host=db;Port=5432;Database=shopping_db;Username=shopping_user;Password=shopping_pass"
    networks:
      - shoppingnet

  # Uncomment the following lines to use a PostgreSQL database
  # db:
  #   image: postgres:15
  #   container_name: shopping_db
  #   environment:
  #     POSTGRES_USER: shopping_user
  #     POSTGRES_PASSWORD: shopping_pass
  #     POSTGRES_DB: shopping_db
  #   networks:
  #     - shoppingnet

volumes:
  sqlite_data:

networks:
  shoppingnet:
    driver: bridge