services:
  frontend:
    image: maeddes/hse25frontend:flask
    container_name: frontend
    ports:
      - "5000:5000"
    environment:
      API_SERVER_URL: "http://api:3000"
    networks:
      - shoppingnet

  api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: shopping_api
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      POSTGRES_CONNECTION: "Host=db;Port=5432;Database=shopping_db;Username=shopping_user;Password=shopping_pass"
    networks:
      - shoppingnet

  db:
    image: postgres:15
    container_name: shopping_db
    environment:
      POSTGRES_USER: shopping_user
      POSTGRES_PASSWORD: shopping_pass
      POSTGRES_DB: shopping_db
    networks:
      - shoppingnet

volumes:
  db_data:

networks:
  shoppingnet:
    driver: bridge